### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jaan143** [BlueHatbRit/mdpdf#109]
first of all thank you for the script
i need some help about pdf file
1. when i convert pdf file inside pdf file every image bellow there is image file name showing which i don't want. file names are like this "image-OUTYI5U9.png"  "image-JY3NLUO9.jpg"
2. i want to increase font size of whole pdf file
3. i want to customize page size but not A4 or latter or A3. So can i add my custom size in inches ? if yes then where can i add it
kindly help me about this

thank you so much

**Comment by BlueHatbRit** [comment]
Hi, no problem I should be able to provide a little help on these.

1. It would be best if you could provide a sample markdown file + assets which I can use to verify some of the issues. I'd suggest uploading it as a public repo on github so it's easier to access.
2.  you'll need to include your own css stylesheet and probably use `--gh-style` to force the default style to be applied if you've not already overridden it.
3. We support the page sizes supported by Chrome (as that's what we use to render out the PDF under the hood). I'm afraid that only supports a limited number of options which you can check on the print to PDF screen in Chrome.

**Comment by jaan143** [comment]
@BlueHatbRit  Dear
where i can send you sample ?
i want to send it as private so if you have email can tell me i will email you
thank you

**Comment by jaan143** [comment]
@BlueHatbRit  i want to use A5 paper size so how can i use 
--format=<A5>
--format=A5

please tell me exact command about it
thank you

**Comment by BlueHatbRit** [comment]
I would suggest sending a minimal example publicly if you can (create a new github repo, or upload a .zip here). We don't need your actual document, just something that will show the issue you're having.

Yes, `--format=A5` should get you an A5 pdf I think, you can checkout the Chrome Puppeteer documentation for specifics but I believe `A5` should work.
