### ISSUE TITLE
UTF-8 chars

### ISSUE THREAD

**Issue by K0F** [BlueHatbRit/mdpdf#110]
Hi, I am not sure if it is typeface problem (?) or somewhat deeper one, but some of Czech letters, to name "ěď" are not rendered at all in resulting PDF (all the settings are default).. an encoding seems to be right in the source document. Thanks for any clue.

**Comment by BlueHatbRit** [comment]
Hi @K0F, we use Shdowdownjs under the hood for markdown -> html before then rendering the html as a PDF via puppeteer. From what I can see Showdownjs handles it just fine and I can't imagine Chrome (Puppeteer) is having an issue so I'd suggest it's _probably_ the default typeface. You can change that through the CSS though, maybe try changing that to some kind of system default that you know will support extended character sets like Czech?

**Comment by K0F** [comment]
Ok thanks, I have suspected it.. it is often the case, I'll try it and let you know. Bests

**Comment by K0F** [comment]
Confirmed, changing typeface did the trick, thanks @BlueHatbRit  for your kind support.

**Comment by BlueHatbRit** [comment]
Glad to hear it, by any chance would you mind sharing what typeface you switched to if it's similar to our default? It might be worth me updating the readme for people who run into this in the future. No problem if you went for something totally different.

**Comment by K0F** [comment]
I used Droid Serif.. I believe it has an open licence

**Comment by K0F** [comment]
TeX Gyre fonts are working as well
