### ISSUE TITLE
Support for styling of .MD structure?

### ISSUE THREAD

**Issue by mariusandersen** [BlueHatbRit/mdpdf#13]
Hello.

I like the way you add a header and footer in this style. I need my outputed .pdf to have a standardized feel to it so I can use it between multiple documents.

I would like however to have more control over the standard .MD structure styling.

For instance, in MD I have:
# My header
## My sub header

I would in the example above like to set both these headers to be color blue.
I would also like to set the sub header to be italic.
I would also like to change font maybe?

Is there any support for this kind of styling?

I don't want to put html div tags into the .md file. I want a nicely readable .md file at the same time as a more custom looking .pdf file

**Comment by BlueHatbRit** [comment]
Hi @mariusandersen great question! This is exactly how mdpdf is designed actually. You can pass in a CSS stylesheet which will help you style the entire document including headers and footers.

mdpdf will convert your markdown file into HTML, attach any required stylesheets and then convert it into a pdf. As such you can set styles on any elements. Here's one for what you were asking.

```css
h1 {
    color: blue;
}

h2 {
    color: blue;
    font-style: italic;
}
```

For fonts it's the same, just use the way you would normally to bring fonts in with CSS.

The fastest way I've found to build this yourself is to run mdpdf under debug on a markdown file (`mdpdf my-doc.md --debug`). This will output a HTML version of the document, you can then use this to check your css changes and debug your CSS errors.

An important thing to note is that mdpdf will disable the pre-existing github-markdown stylesheet when you pass in your own. This means if you pass in a blank stylesheet, things may revert to times new roman etc. You can dig into our "assets" folder to find these styles and add them to your own sheet if needed.

I'm aware this isn't entirely clear in the documentation, I'll see if I can update that in the next week or so. Please ask any further questions you might have!
