### ISSUE TITLE
Empty pdf generating from docker container

### ISSUE THREAD

**Issue by RaviVaranasi** [BlueHatbRit/mdpdf#15]
It works outside the docker container but is empty when running within docker container. FYI: using centos operating system docker image.

**Comment by BlueHatbRit** [comment]
@RaviVaranasi Are you able to provide some code / container samples to help recreate the issue?

**Comment by RaviVaranasi** [comment]
I figured out the problem - 

I needed to install font libraries for centos

```
yum install -y yum-plugin-ovl fontconfig freetype urw-fonts;
```

**Comment by BlueHatbRit** [comment]
Brilliant, glad you're sorted!
