### ISSUE TITLE
Header images not resolving

### ISSUE THREAD

**Issue by BlueHatbRit** [BlueHatbRit/mdpdf#18]
@Stranger-Ok has reported that header images are not being resolved correctly. It seems the image resolving code is running before the header and footers are being injected into the layout.

**Comment by BlueHatbRit** [comment]
Fixed by #20!

**Comment by lud** [comment]
It does not work for me.

Please see this small example. run `make install` and `make` to run the sample.


[mdbug.zip](https://github.com/BlueHatbRit/mdpdf/files/4107946/mdbug.zip)

**Comment by lud** [comment]
One option could be to base64 encore images `src`
