### ISSUE TITLE
Resolving images from API and from command working differently.

### ISSUE THREAD

**Issue by Stranger-Ok** [BlueHatbRit/mdpdf#19]
@BlueHatbRit Hello, I found another issue, that's related to images resolving.
If I run mdpfd from command line, converting completes successfully, but if I call from API  "mdpdf.convert(options)" . I'm getting an exception "TypeError: Path must be a string. Received undefined" on resolving image path to URL. Can you try figure out whats wrong?

**Comment by BlueHatbRit** [comment]
Can you provide an `options` object which was causing the issue so I can narrow it down?

**Comment by Stranger-Ok** [comment]
@BlueHatbRit Yes, here it is full test scenario.
https://drive.google.com/file/d/0B5ZtuDBysaLJWVF0Y2FwalN6QVE/view?usp=sharing

If I run "grunt convertMdToPdfTask" converting completes correctly.
If I run "grunt convertMdToPdf_SE" I'm getting an error.

**Comment by BlueHatbRit** [comment]
@Stranger-Ok wonderful thanks, just as a note GitHub Gists are really good for this stuff in the future to save using up Google Drive space :) I'll take a look into it this evening if I can. Feel free to have a poke around yourself as well and see if you can resolve it if you'd like to!

**Comment by BlueHatbRit** [comment]
@Stranger-Ok This is now solved by PR #21, I've tested it with headers and footers as well just to be doubly sure it works.

**Comment by BlueHatbRit** [comment]
@Stranger-Ok both the issues you dug up have been resolved and shipped as 1.3.4 on NPM. Thanks for your help!
