### ISSUE TITLE
00:00:00 rendered as 00[]00

### ISSUE THREAD

**Issue by higab85** [BlueHatbRit/mdpdf#22]
Hey! I'm using ubuntu, so I imagine the [] is supposed to be an emoji, but it's still not the intended outcome. Any chance of giving an ignore emoji option? Cheers !! 

By the way. This is the best md to pdf CLI software out there. Gets the job done, quickly and efficiently. Thank you for this :)

**Comment by BlueHatbRit** [comment]
Hi @higab85 first thanks so much for the kind words, it's so encouraging and has made my day.

Interesting case, I'll add a toggle for now as you've suggested but later I might come back and try and fix this within the emoji library we're using so we don't even need the toggle.

**Comment by BlueHatbRit** [comment]
@higab85 I've published an update as 1.3.5 on npm which includes the documented `--noEmoji` flag which will turn off emoji conversions :)

**Comment by higab85** [comment]
@BlueHatbRit  Awesome!! Thank you very much :)
