### ISSUE TITLE
Single --border option?

### ISSUE THREAD

**Issue by danielbayley** [BlueHatbRit/mdpdf#25]
Maybe a single `--border=<size>` flag would be useful for situations where you just want an equal border without having to specify all 4 options?

Also, maybe have shorter options like `-b` in this case for example…

**Comment by BlueHatbRit** [comment]
I could see this being useful, how would you propose it should function if a user entered `--border` and `--border-left`?

**Comment by danielbayley** [comment]
@BlueHatbRit I suppose it could work similar to how CSS does and just override it… so `--border=10` along with `--border-bottom=15` would give you a border of 10 all around, except at the bottom, which would be 15.

**Comment by BlueHatbRit** [comment]
Great idea, I've put a beginner tag on this issue as it should be straight forward for a new contributor to add. If no one pipes up then I might be able get to it in a week or so!

**Comment by uschek** [comment]
Just made a PR. :)
