### ISSUE TITLE
Consider Midas for syntax highlighting?

### ISSUE THREAD

**Issue by danielbayley** [BlueHatbRit/mdpdf#26]
http://midasjs.com
https://github.com/ben-eb/midas

**Comment by BlueHatbRit** [comment]
Cheers for the suggestion, I've not seen midasjs and I can't seem to find any sort of list of languages it supports. Any ideas where this can be found so I can take a deeper look at it?

**Comment by danielbayley** [comment]
Ah, I didn't realise it was _only_ for highlighting CSS… The fact that it was built on PostCSS is what got me thinking it might be really nice for theming, but CSS only is probably of too limited application for this project…

**Comment by BlueHatbRit** [comment]
Ahh, that explains why I couldn't find a list! Great suggestion though, if you happen to find a better one that highlight.js then do let me know :)

**Comment by danielbayley** [comment]
@BlueHatbRit Check out https://github.com/wooorm/lowlight#lowlight--

**Comment by BlueHatbRit** [comment]
@danielbayley at the moment the syntax highlighting is added when the markdown renders inside a headless browser. Highlight JS automatically goes through each code block and applies the correct highlights. Lowlight would require mdpdf to do that for each code block in the node process before injecting it into the headless browser.

I'm curious as to why you're after a different syntax highlighting engine. It would be good to know your use case before changing the highlighting engine. I'm aware it's not working for Windows (#11), is that the platform you're using mdpdf with?
