### ISSUE TITLE
Space inside inline code renders to a checkbox

### ISSUE THREAD

**Issue by istvanszoboszlai** [BlueHatbRit/mdpdf#33]
Version: 1.5.1

This
```
*format:* `yyyy-MM-dd HH:mm:ss.SSS`  
```
renders to this
<img width="338" alt="screen shot 2017-11-07 at 1 34 41" src="https://user-images.githubusercontent.com/292224/32471105-ea1f82d4-c35b-11e7-91ae-324c3bdd03d6.png">

**Comment by BlueHatbRit** [comment]
Thanks for reporting this @istvanszoboszlai!

This is actually not a checkbox, it's actually part of the emoji code which we're working on in #30. I'm working with the folks on Bloggify/showdown-emoji to try and figure this one out. I'm going to close this as a duplicate as it's now linked to that original issue.

I'll continue some discussion on there.

**Comment by istvanszoboszlai** [comment]
Just for the record: in osX's Preview app, when I clicked on it, I got a checkbox inside the box. Hence the description :)
Thanks for the fast feedback.

**Comment by BlueHatbRit** [comment]
Oh wow, that's a new one! I'll have to test that out myself, it's probably because of the default image it's using I imagine, that may be a nice way to include checkboxes though!

**Comment by BlueHatbRit** [comment]
This has now been fixed with #30
