### ISSUE TITLE
Messed-up Kerning on Windows

### ISSUE THREAD

**Issue by Crissov** [BlueHatbRit/mdpdf#36]
No matter which stylesheet or font I'm using, the PDF shows up with completely messed up kerning. Some letters are too far apart, some are too close together, and that regularly happens within a single word. The letter sequences closer together seem to be the same ones throughout the document. Explicitly setting `letter-spacing: 0` has no effect.

**Comment by BlueHatbRit** [comment]
Wow that isn't good! Are you able to provide a stylesheet example and the generated PDF? I have limited access to a windows machine at the moment so it'll help speed up the debugging process.

**Comment by Crissov** [comment]
- MD: <https://github.com/Crissov/unicode-proposals/blob/master/hearts.md>
- PDF without custom CSS: <https://github.com/Crissov/unicode-proposals/blob/master/hearts.pdf>
- PDF with custom CSS: <https://github.com/Crissov/unicode-proposals/blob/master/hearts-print.pdf> <https://github.com/Crissov/unicode-proposals/blob/master/print.css>

**Comment by BlueHatbRit** [comment]
@Crissov thanks for supplying those files, clearly the kerning is off in the final PDF as you've said.

I should have access to a windows machine this evening so I'm going to try and give it a run through then and see if I can debug it a little bit. The rendering of the PDF is handled by phantomjs so I'm not sure how much control I can impose over it other than with some crafty css. I'll take a deeper dive when I get onto my windows machine and then I might be able to see about bumping some versions to try and bring in the latest phantomjs and see if that solves the issue.

**Comment by BlueHatbRit** [comment]
I've been working on the Puppeteer migration and it's not far off being finished. I can confirm that this fixes the kerning issues :tada:, it shouldn't be long until this is finished. You can track the progress on PR #42

**Comment by BlueHatbRit** [comment]
This should be resolved with the 2.0.0 Puppeteer based release but please check the release notes before upgrading!
