### ISSUE TITLE
Styles are not applied

### ISSUE THREAD

**Issue by 8lank** [BlueHatbRit/mdpdf#37]
Hi,

First of all, thank you for your amazing tool. I recently started using it and I noticed that whatever the CSS style sheet provided, the styles are not applied.

I am using a MacBook Pro and I installed mdpdf globally using the npm command line.

Best

**Comment by BlueHatbRit** [comment]
Hello @8lank, thanks for the encouragement! Are you able to provide me with the following so I can reproduce the error exactly as you are?

* The version you're running (mdpdf --version)
* The full command you're using
* An example markdown and css file

From that I can run it through quickly and see exactly what might be going wrong!

**Comment by 8lank** [comment]
My bad, I found an issue with my script that was overriding my styles. 

Sorry for that, your tool works perfectly 👍

**Comment by BlueHatbRit** [comment]
Oh that's great news! I'll close this issue then, if you have any more issues then feel free to file another, and feel free to give some tool feedback as well! I'm on twitter, email, or you can just drop an issue (or comment on here). Feedback is amazing as I often have no idea how people are using my tools 😄
