### ISSUE TITLE
Styles seem to not be applied when using js API

### ISSUE THREAD

**Issue by travs** [BlueHatbRit/mdpdf#43]
Styles are applied when using the cli, as in `mdpdf sample.md --style=sample.css`, but seem not to be applied when doing the same via the js API.

Sample:

```
await mdpdf.convert({source: './sample.md', destination: './sample.pdf', styles: './sample.css'})
```

[`sample.md`](https://gist.githubusercontent.com/travs/ef674d6462f8229a5641ac53a11daafd/raw/480b54af882ef6307a22849f5df4e77f78f05e38/sample.md)

[`sample.css`](https://gist.github.com/travs/0e02e09e804669599757a97a85eaf9ee)

[Actual output pdf](https://github.com/travs/markdown-pdf/files/1310607/current_version.pdf)

[Expected output pdf](https://github.com/travs/markdown-pdf/files/1310608/earlier_version.pdf)

High chance it is me doing something wrong, since I looked at your code and not sure where this could happen.

Discovered when investigating [this](https://github.com/travs/markdown-pdf/issues/165)

**Comment by BlueHatbRit** [comment]
The best place to check for this stuff is in bin/index.js, I'm aware it's a bit messy but it's where we take CLI arguments and parse them into the format accepted by the mdpdf JS api, this api is the same as the one exported for public consumption.

The JS api needs full file paths as you should be able to see on line 100 where we call `path.resolve(style);`.

Apologies that this isn't clear, we definitely need a documentation update and refresh. I also need to get in some better argument validation for this! Any validation has been a bit lazy in the API so far as the CLI was the main way people were accessing it. Once the puppeteer implementation is complete, I'll be moving onto a refactor which should also make room for some better arg validation from both the API and CLI. There will be issues cropping up on the repo here soon.

If the above doesn't work then do ping this issue again, i'll leave it open until it's properly resolved.

**Comment by travs** [comment]
Ahh ok gotcha. Yeah I tried it again and I think I may have been mistaken in the first place about the output. When I used `defaultStyles: true` it produced exactly what I expected, which is really great. Sorry about this one :)

**Comment by BlueHatbRit** [comment]
No worries, just means the docs need to be better!
