### ISSUE TITLE
Error rendering pictures to the PDF

### ISSUE THREAD

**Issue by enric1994** [BlueHatbRit/mdpdf#51]
After running `mdpdf README.md`, the pictures appear as **interrogation** **signs**.
I am using this syntax in the Markdown file: `![Alt text](/reports/figures/demo.png)`

Any advice?

Thanks!

**Comment by BlueHatbRit** [comment]
Hi @enric1994 a couple of questions if you don't mind, they should help me figure out what's going on.

1. What OS are you using?
2. What do you mean by "Interrogation signs", is there anyway you could reproduce this and attach a screenshot or the a markdown file + image + the command you're using?
3. In your example you're using an absolute path on unix platforms, is that correct or are you using relative pathing? This shouldn't make a difference but it's useful to check!

**Comment by enric1994** [comment]
I am using a this Docker image:
```
FROM node:8.11.1
RUN npm i -g phantomjs-prebuilt --unsafe-perm --silent
RUN npm install mdpdf -g
```

![screenshot from 2018-10-02 13-59-20](https://user-images.githubusercontent.com/17545224/46349948-69857180-c64b-11e8-9da5-3f64b7a288f9.png)

.
├── docker
│   ├── docker-compose.yml
│   └── Dockerfile
├── docs
│   └── README.pdf
├── Makefile
├── README.md
├── reports
│   └── figures
│       └── demo.png


Okay... I changed the path and it works: `![Alt text](reports/figures/demo.png)`

Thanks!

**Comment by BlueHatbRit** [comment]
No worries, in unix if you prefix the path with a `/` it'll start at the root if your operating system. You can see this by doing `cd /reports/figures/demo.png` vs `cd reports/figures/demo.png` in your terminal.

Thanks for the quick turn around!

Feel free to leave some feedback on mdpdf just as a comment in this issue if you like, it's always good to know what people are using mdpdf for and what they like / dislike about it. It helps me get an idea of the audience!

**Comment by enric1994** [comment]
Well, I use it basically to put all the .md's in a "docs" folder, maybe I add this automation to my enric1994/mdpdf Docker container, something like `make docs`. I will let you know.
