### ISSUE TITLE
Bold sections are not rendered as bold

### ISSUE THREAD

**Issue by mitesh-mokko** [BlueHatbRit/mdpdf#59]
Using node.js 9.11.2 on a MacBook Pro (MacOS Mojave), the following file does not render bold as bold.

This issue persists whether we use raw styles, github styles or even custom styles.

We have also tested with **bold** and __bold__ and in each case the font remains normal.

**Comment by BlueHatbRit** [comment]
This is very strange, do you have a sample markdown file and pdf output so I can make sure I'm getting the same effect as you? I've not had this issue before.

**Comment by mitesh-mokko** [comment]
Hi! Thanks for your reply.

The sample file that we used was along the lines of:

```
# Heading
## Heading
### Heading

**Bold**
*Emphasis*

Normal Text Here..
```

The "Bold" piece does not render as **Bold**, but only on my laptop - locally. When the same code is deployed to an Ubuntu VPS, everything works just fine!

We checked the generated HTML (debugging step) and that looks perfectly fine - so it could be an issue with html-pdf..

**Comment by BlueHatbRit** [comment]
Huh, that's super strange... If the HTML is fine then it'll be an issue with Phantom which is the embedded browser used to do the render. I'm in the process of replacing this with Puppeteer (#42) but I've had literally no time recently due to family issues and the holidays.

Can you give your full macos version number? I run mac at home and at work so should be able to give it a test if I'm on the same versions as you.

**Comment by mitesh-mokko** [comment]
It is most likely PhantomJS; and this is a minor issue for the moment.

My MacOS version: 10.14.2 (macOS Mojave)

I'm a Puppeteer novice, but willing to assist!

**Comment by BlueHatbRit** [comment]
Checkout the Puppeteer branch if you want to see where things are at, it should work fine if you're not using headers and footers. Currently puppeteer is quite incomplete with these two features which is a huge shame. #42 shows the branch. That branch should solve the issue, would you mind checking when you get some time @mitesh-mokko?

**Comment by mitesh-mokko** [comment]
Wonderful. I'll check.

**Comment by mitesh-mokko** [comment]
Just tested with the updated package (2.0.0) and this particular issue is solved.

**Comment by BlueHatbRit** [comment]
Wonderful, thanks for the confirmation!
