### ISSUE TITLE
"Failed to download Chromium r609904!" when installing

### ISSUE THREAD

**Issue by brunodantas** [BlueHatbRit/mdpdf#60]
```
sudo npm install mdpdf -g
/usr/local/bin/mdpdf -> /usr/local/lib/node_modules/mdpdf/bin/index.js

> puppeteer@1.11.0 install /usr/local/lib/node_modules/mdpdf/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r609904! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/mdpdf/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/mdpdf/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.11.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by brunodantas** [comment]
Solved with the following line. The environment variable needed to be all lowercase.

`sudo npm config set puppeteer_skip_chromium_download true -g`

**Comment by BlueHatbRit** [comment]
> Error: EACCES: permission denied, mkdir

This line confuses me as you installed using sudo, did you get the same error using non-sudo install? Are you behind a proxy or corporate firewall by any chance? I'm wondering if any of that could also cause the download to fail somehow thus resulting in an issue further down the line.

**Comment by brunodantas** [comment]
I couldn't install without sudo either, but I don't remember the error. I was not using any proxy or firewall as far as I know.

**Comment by ShaulEngler** [comment]
this happens without sudo in an `ubuntu:16.04` based docker image
with node 8 and npm 6.1.0
when executing:
`RUN npm install -g mdpdf@2.0.1`

tried to `--unsafe-perm` which solved installation but failed in usage

**Comment by BlueHatbRit** [comment]
That's incredibly strange, I'll try this over the weekend and see if I can recreate it. I don't quite know how that could be anything in the code of this module, it feels like an issue with either puppeteer or npm but if I can recreate it then I can dig further. @ShaulEngler, are you behind any sort of proxy?
