### ISSUE TITLE
Specifying highlight.js theme?

### ISSUE THREAD

**Issue by thekevinscott** [BlueHatbRit/mdpdf#62]
Hi there! Just stumbled across this and I really dig what `mdpdf` can do so far.

Is there a way to modify the default highlight.js styles?

I've played around with manually overriding CSS (aka, `.markdown-body .highlight pre`) which works fine, but I'd love to be able to switch hljs themes without manual CSS.

I didn't see anything in the documentation though I do see some closed issues around highlighting, but nothing regarding switching styles.

**Comment by BlueHatbRit** [comment]
We don't have anything for this right now but I'd be open to a pull request if you want to add it. Mdpdf is about customisation so if we can find a tidy way to include further customisation then that would be neat, but as you said you could include a full override of the styles in a custom css file. This would make your css file quite large but it does mean it's possible.

If you have a proposal, feel free to add it to this issue or submit a pull request and I'd be really happy to look it over. It's worth me mentioning though that I probably don't have time to implement a proposal myself right now, so if this is something you'd really value then a PR might be the best way to go 😄

**Comment by thekevinscott** [comment]
That makes sense.

I ended up wanting to go with a theme from PrismJS, so what I'm doing is preprocessing code blocks myself as `<pre />`s and applying the appropriate prism class name, and including the stylesheet in the css file.

Works for my use case, so I'm going to close this issue.
