### ISSUE TITLE
Support for custom page numbers

### ISSUE THREAD

**Issue by thekevinscott** [BlueHatbRit/mdpdf#63]
I'm trying to generate a PDF with the intro pages numbered `i ... iv`, and the 5th page starting at 1.

In the README it's stated that Puppeteer has considerably less support for header and footer styling, and I can't find anything that would indicate control over manipulating the page numbers directly. [This thread](https://github.com/GoogleChrome/puppeteer/issues/2167#issuecomment-425448926) seems to point to arbitrary Javascript being executed within the context of the header file, but I can't get it to run and I'm not sure how I'd leverage the page content to indicate which page number to display.

Is this a no go until Puppeteer introduces better header support? Or have others found a workaround for this issue?

**Comment by BlueHatbRit** [comment]
Puppeteer doesn't support much in the way of page number configuration as you've noted, the thread you linked seems interesting and I feel like it might be possible to use that sort of approach but I'll be honest in that I don't quite know when the JS would be executed or how you'd determine what page you're on (especially if the JS is executed before the pdf is formatted into split pages).

If you attach your code, I could try and have a look but I suspect page numbers are done by the pdf system and are split apart from the document content in which case we'd need an api to interact with in puppeteer sadly.

**Comment by thekevinscott** [comment]
I've dug a little bit deeper, and from what I can tell there's very little configuration ability on the Puppeteer side.

Is it fair to say that #31 is also blocked by lack of support for a better puppeteer page numbers API?

I may look into a tool like hummusjs, which ostensibly is a tool for stitching together PDFs, and combine with `mdpdf` to try and generate custom page numbers, but I think I'll still be blocked on the generation of a Table of Contents... and not really sure of any way to get around that :/

**Comment by thekevinscott** [comment]
I was able to achieve what I needed with a combination of `mdpdf` and `hummusjs`.

My workflow is to write out each chapter as a separate PDF file with `mdpdf`, add page numbers with `hummusjs`, and then (presumably) create a Table of Contents also with `hummusjs`.

Bummer to not do everything in `mdpdf` but I think its hands are tied by Puppeteer's limitations for now.

Thanks again for an awesome library!
