### ISSUE TITLE
Option --no-emoji not working

### ISSUE THREAD

**Issue by josefhammer** [BlueHatbRit/mdpdf#66]
Hi,

I have the issue that in the code section of a document there are several `:x:` which are converted to emojis.

For one thing, I was surprised that emoji-conversion takes place in pre-formatted text ... I would not expect that. Anyway, when I tried to switch off the conversion with '--no-emoji', the conversion still happens.

Any idea on how to disable the conversion?

Thanks a lot,
Josef

**Comment by josefhammer** [comment]
After looking at the source code I tried `--noEmoji` which seems to work.

**Comment by BlueHatbRit** [comment]
Oh that's peculiar, thanks for reporting this I'll fix the flag / documentation. Thanks!
