### ISSUE TITLE
code syntax highlighting broken

### ISSUE THREAD

**Issue by hoob3rt** [BlueHatbRit/mdpdf#89]
I can pretty easily break syntax highlighting in the whole file if i leave out a single code element without specified language
![bug](https://user-images.githubusercontent.com/41551030/77863099-22684480-7220-11ea-9a3f-afd8c14ea6e2.png)

**Comment by BlueHatbRit** [comment]
Hi @hoob3rt thanks for reporting this, we use a dependency called highlightjs for this and don't have much control over it's processing of the syntax highlighting.

This may be something that's resolved in a newer version of highlight so I'll see if I can bump the version when I get some time (unless someone wants to submit a pr). If this is still persent in more recent versions of highlight then the bug should probably be logged with that project - https://github.com/highlightjs/highlight.js if I get time then I'll try bumping the version over soon and if it's still there I can raise the bug, if anyone wants this fixed more urgently then I'd suggest trying to update the package we've pulled in and update this issue with the results 😄

Thanks again for the report, sorry it's causing problems!

**Comment by ncpenke** [comment]
I ran into the same issue and thought syntax highlighting wasn't supported at all. Running it through showdown-highlight (which internally also uses highlightjs) seems to work ok. Please let me know if you're interested in taking the patch:

https://github.com/ncpenke/mdpdf/commit/c4d3b64e723ed89d4b064b249000f2c5a5a300f2

**Comment by BlueHatbRit** [comment]
Hey @ncpenke that looks great and much more stable, I'd definetely be interested in taking that patch. Would you like to open a PR for it? Don't worry about purging my implementation of highlightjs, I can rip that out before releasing.

**Comment by ncpenke** [comment]
Great! PR here: https://github.com/BlueHatbRit/mdpdf/pull/90. Please let me know if you'd like me to make any further cleanup.

**Comment by BlueHatbRit** [comment]
Thanks for that @ncpenke, and you're welcome it's great to see people finding value in this years after I built it!

I'll get that reviewed and will try and rip out the existing highlightjs asap, i'll post back here and in the PR when there's been a release.

**Comment by BlueHatbRit** [comment]
That's been merged into master and tagged as 2.1.2, I'm going to do some more testing before pushing it to npm, if anyone else is able to do a quick test that would be smashing!

**Comment by BlueHatbRit** [comment]
2.1.2 has gone out on npm now and should be available for download. Thanks for your contributions everyone 🚀

**Comment by ncpenke** [comment]
I just did a test on 2.1.2 and it works as expected! Thanks again for incorporating this so quickly!

**Comment by BlueHatbRit** [comment]
No problem, thanks for the code submission. It's always a lot lot easier to find time to do clean up, testing, and a release rather than implement a full feature of track down a bug from an issue. I try to pay respect to people who are able to and have the time to submit code changes, it's really appreciated and helps me (and the users) massively.
