### ISSUE TITLE
How to resize the image

### ISSUE THREAD

**Issue by norma-jeane-m** [BlueHatbRit/mdpdf#97]
Hi, How can I change the size of an image in markdown?
I usually used to the beyond two methods.

```
![](./sample.png =100x20)
![](./sample.png =250x)
```

But when I converted from markdown to pdf using mdpdf, it didn't work it well..

Please give me some advice..

**Comment by BlueHatbRit** [comment]
The markdown specification is quite... weak. Lots of different places implement it differently, we use Showdownjs as our markdown engine so they determine much of the implementation. Showdown doesn't handle image resizing that way sadly. Thankfully, you can just change your markdown image line into a line of html and it should work.

```
<img src="./sample.png" width="100" height="20"/>
```

**Comment by norma-jeane-m** [comment]
Thank you so much!

**Comment by BlueHatbRit** [comment]
No problem :)
